'use strict';
const $=id=>document.getElementById(id);
let db,key,config,profile,records=[],pendingImport=null,attachment=null,previewURL=null,recorder=null,stream=null,chunks=[],timer=null,started=0,cancelled=false,urls=[],busy=false,lastActive=Date.now(),toastTimer;
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s)};
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function seal(value){return value}
async function open(value){return value}
function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open('fabietto-local-v1',1);request.onupgradeneeded=()=>{request.result.createObjectStore('config');request.result.createObjectStore('messages',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function read(store,id){return new Promise((resolve,reject)=>{const request=db.transaction(store).objectStore(store).get(id);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function all(){return new Promise((resolve,reject)=>{const r=db.transaction('messages').objectStore('messages').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function write(store,value,id){return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');const s=tx.objectStore(store);id===undefined?s.put(value):s.put(value,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
function replaceDatabase(c,items){return new Promise((resolve,reject)=>{const tx=db.transaction(['config','messages'],'readwrite');tx.objectStore('config').put(c,'main');const s=tx.objectStore('messages');s.clear();items.forEach(item=>s.put(item));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000)}
function renderProfile(){$('contact-title').textContent=profile.name;$('avatar').replaceChildren();if(profile.photo){const img=document.createElement('img');img.src=profile.photo;img.alt='';$('avatar').append(img)}else $('avatar').textContent='🤍';$('backup-status').textContent=config.lastBackup?'Ultima esportazione: '+new Date(config.lastBackup).toLocaleString('it-IT'):'Nessun backup esportato su questo dispositivo.'}
function dataBlob(data){const [header,body]=data.split(',');const mime=header.match(/^data:([^;]+);base64$/)?.[1];if(!mime)throw Error('Formato allegato non valido.');return new Blob([unb64(body)],{type:mime})}
function mediaNode(record,preview=false){let node;if(record.type==='image'){node=document.createElement('img');node.alt=record.name||'Foto nella chat';node.loading='lazy'}else{node=document.createElement(record.type==='audio'?'audio':'video');node.controls=true;node.preload='metadata';if(record.type==='video')node.setAttribute('playsinline','')}
const url=URL.createObjectURL(dataBlob(record.value));node.src=url;urls.push(url);return node}
function render(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[];const messages=$('messages');messages.replaceChildren($('empty'));$('empty').hidden=records.length>0;let previous='';for(const r of records){const date=new Date(r.date),day=date.toLocaleDateString('it-IT',{day:'numeric',month:'long',year:'numeric'});if(day!==previous){const divider=document.createElement('div');divider.className='day';const label=document.createElement('span');label.textContent=date.toDateString()===new Date().toDateString()?'Oggi':day;divider.append(label);messages.append(divider);previous=day}const bubble=document.createElement('article');bubble.className='bubble';if(r.type==='text'){const p=document.createElement('p');p.textContent=r.value;bubble.append(p)}else bubble.append(mediaNode(r));const time=document.createElement('time');time.className='time';time.dateTime=date.toISOString();time.textContent=date.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});bubble.append(time);messages.append(bubble)}requestAnimationFrame(()=>messages.scrollTop=messages.scrollHeight)}
async function saveMessage(message){if(!key)throw Error('Apri la chat per salvare il messaggio.');const r={...message,date:Date.now(),id:crypto.randomUUID()};const payload=await seal(r);await write('messages',{id:r.id,payload});records.push(r);render()}
async function send(event){event.preventDefault();const value=$('message-input').value.trim();if(!value||busy)return;busy=true;$('send').disabled=true;try{await saveMessage({type:'text',value});$('message-input').value='';composerState()}catch{toast('Messaggio non salvato. Verifica lo spazio libero e riprova.')}finally{busy=false;$('send').disabled=false}}
function composerState(){const input=$('message-input');$('send').hidden=!input.value.trim();$('voice').hidden=!!input.value.trim();input.style.height='44px';input.style.height=Math.min(130,input.scrollHeight)+'px'}
const fileData=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});
async function chooseAttachment(){const file=$('attachment-input').files[0];$('attachment-input').value='';if(!file)return;if(file.size>50*1024*1024){toast('Questo file supera 50 MB. Scegli un video più breve o un file più piccolo.');return}const type=file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':null;if(!type){toast('Scegli una foto o un video. Per HEIC, esporta una copia JPEG da Foto.');return}attachment={type,file,name:file.name};previewURL=URL.createObjectURL(file);const node=document.createElement(type==='image'?'img':'video');node.src=previewURL;if(type==='video'){node.controls=true;node.setAttribute('playsinline','')}else node.alt='Anteprima della foto';$('media-preview').replaceChildren(node);$('attachment-name').textContent=file.name+' · '+(file.size/1024/1024).toFixed(1)+' MB';$('media-dialog').showModal()}
async function saveAttachment(){if(!attachment||busy)return;busy=true;$('save-attachment').disabled=true;try{await saveMessage({type:attachment.type,name:attachment.name,value:await fileData(attachment.file)});$('media-dialog').close()}catch{toast('Allegato non salvato. Verifica lo spazio libero e riprova.')}finally{busy=false;$('save-attachment').disabled=false}}
function releaseMedia(){attachment=null;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;$('media-preview').replaceChildren()}
async function startRecording(){if(recorder||busy)return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('La registrazione non è disponibile. Apri il sito in Safari aggiornato.');return}busy=true;try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));recorder=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream);chunks=[];cancelled=false;recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{const type=recorder.mimeType;stream.getTracks().forEach(t=>t.stop());stream=null;recorder=null;clearInterval(timer);$('recording').hidden=true;$('composer').hidden=false;if(!cancelled){busy=true;try{const blob=new Blob(chunks,{type});await saveMessage({type:'audio',value:await fileData(blob),name:'Messaggio vocale'})}catch{toast('Vocale non salvato. Verifica lo spazio libero e riprova.')}finally{busy=false}}chunks=[]};recorder.start();started=Date.now();$('record-time').textContent='0:00';$('recording').hidden=false;$('composer').hidden=true;timer=setInterval(()=>{const seconds=Math.floor((Date.now()-started)/1000);$('record-time').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');if(seconds>=300){toast('Raggiunti 5 minuti: il vocale viene salvato.');stopRecording(false)}},500)}catch{stream?.getTracks().forEach(t=>t.stop());stream=null;toast('Consenti l’accesso al microfono nelle impostazioni di Safari, poi riprova.')}finally{busy=false}}
function stopRecording(cancel){cancelled=cancel;if(recorder?.state==='recording')recorder.stop()}
async function backup(){if(busy||!key)return;busy=true;$('backup').disabled=true;try{const messages=await all();const body=JSON.stringify({format:'fabietto-chat',version:1,config,messages});const url=URL.createObjectURL(new Blob([body],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='chat-backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);config.lastBackup=Date.now();await write('config',config,'main');renderProfile();toast('Backup preparato. Conservalo in File: contiene i tuoi messaggi e allegati.')}catch{toast('Impossibile esportare il backup. Riprova.')}finally{busy=false;$('backup').disabled=false}}
async function chooseBackup(){const file=$('backup-input').files[0];$('backup-input').value='';if(!file)return;if(busy||recorder){toast('Termina prima il salvataggio o la registrazione.');return}busy=true;try{const imported=JSON.parse(await file.text());if(imported.format!=='fabietto-chat'||imported.version!==1||!Array.isArray(imported.messages)||imported.messages.some(r=>typeof r.id!=='string'||!r.payload||!['text','image','video','audio'].includes(r.payload.type)||typeof r.payload.value!=='string'||!Number.isFinite(r.payload.date))||new Set(imported.messages.map(r=>r.id)).size!==imported.messages.length)throw Error();for(const r of imported.messages){if(r.payload.type!=='text'){const blob=dataBlob(r.payload.value);if(!blob.type.startsWith(r.payload.type+'/'))throw Error()}}if(!confirm('Il backup sostituirà i messaggi su questo dispositivo. Esporta prima quelli attuali se vuoi conservarli. Continuare?'))return;await replaceDatabase(config,imported.messages);records=imported.messages.map(r=>({...r.payload,id:r.id})).sort((a,b)=>a.date-b.date);render();$('settings').close();toast('Backup ripristinato.')}catch{toast('Backup non valido o spazio insufficiente. La chat attuale è conservata.')}finally{busy=false}}
$('composer').addEventListener('submit',send);$('message-input').addEventListener('input',composerState);$('attach').onclick=()=>$('attachment-input').click();$('attachment-input').onchange=chooseAttachment;$('save-attachment').onclick=saveAttachment;$('media-dialog').addEventListener('close',releaseMedia);$('voice').onclick=startRecording;$('cancel-record').onclick=()=>stopRecording(true);$('stop-record').onclick=()=>stopRecording(false);$('menu-button').onclick=$('profile-button').onclick=()=>$('settings').showModal();document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('backup').onclick=backup;$('restore').onclick=()=>$('backup-input').click();$('backup-input').onchange=chooseBackup;
window.addEventListener('pagehide',()=>{if(recorder)stopRecording(true)});
(async()=>{try{db=await database();config=await read('config','main');if(!config){config={version:1,lastBackup:null};await write('config',config,'main')}key=true;profile={name:'Fabietto🦋🤍',photo:'fabietto.png'};records=(await all()).map(r=>({...r.payload,id:r.id})).sort((a,b)=>a.date-b.date);$('chat').hidden=false;render();renderProfile();navigator.storage?.persist?.().catch(()=>{});}catch{$('chat').hidden=false;$('composer').hidden=true;toast('Salvataggio non disponibile. Apri in Safari senza navigazione privata.')}})();
if(window.visualViewport){const resize=()=>{document.documentElement.style.setProperty('--app-height',window.visualViewport.height+'px');if(!document.querySelector('dialog[open]'))window.scrollTo(0,0)};window.visualViewport.addEventListener('resize',resize);resize()}
